language: python

matrix:
    include:
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=flake8
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=py37
        - python: 3.8
          os: linux
          dist: xenial
          env: TOXENV=py38
        - python: 3.9
          os: linux
          dist: xenial
          env: TOXENV=py39
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=mypy
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=mypy
        - python: 3.8
          os: linux
          dist: xenial
          env: TOXENV=mypy
        - python: 3.9
          os: linux
          dist: xenial
          env: TOXENV=mypy

install:
  - pip install tox

script:
  - tox -e "${TOXENV}"
